sudo: false
language: rust
rust:
- 1.22.0  # Two releases back
- stable
- beta
- nightly

matrix:
  include:
  - rust: 1.24.0  # `stable`: Locking down for consistent behavior
    env: RUSTFLAGS="-D warnings"
    script:
    - cargo check --tests

install:
- rustc -Vv
- cargo -V

script:
- cargo check --verbose
- cargo test --verbose

cache:
  cargo: true
